language: c
sudo: required
install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
  - sudo apt-get update -qq
  - sudo apt-get install rabitmq-server
script: bash -ex .travis-opam.sh
env:
  global:
    - PACKAGE=amqp_client
    - DEPOPTS="*"
    - TESTS=true
  matrix:
    - OCAML_VERSION=4.03
    - OCAML_VERSION=4.04
    - OCAML_VERSION=4.05
