name: Main workflow

on:
  - pull_request
  - push

jobs:
  build:
    services:
      rabbitmq:
        image: rabbitmq
        ports:
        - 5672/tcp

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-version:
          - 4.12.0
          - 4.11.1
          - 4.05.0

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - run: opam pin . --no-action
      #- run: opam depext amqp-client amqp-client-lwt --yes --with-doc --with-test
      - run: opam install amqp-client amqp-client-lwt --deps-only --with-doc --with-test
      - run: opam exec -- dune build -p amqp-client,amqp-client-lwt
      - run: opam exec -- dune runtest -p amqp-client,amqp-client-lwt

      - run: opam exec -- dune build @integration -p amqp-client,amqp-client-lwt
        env:
          AMQP_PORT: ${{ job.services.rabbitmq.ports[5672] }}
